// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Filter_HW.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Filter_HW::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Filter_HW::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Filter_HW::ap_ST_fsm_state1 = "1";
const sc_lv<4> Filter_HW::ap_ST_fsm_state2 = "10";
const sc_lv<4> Filter_HW::ap_ST_fsm_state3 = "100";
const sc_lv<4> Filter_HW::ap_ST_fsm_state4 = "1000";
const sc_lv<32> Filter_HW::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Filter_HW::ap_const_lv32_1 = "1";
const sc_lv<32> Filter_HW::ap_const_lv32_2 = "10";
const sc_lv<32> Filter_HW::ap_const_lv32_3 = "11";
const bool Filter_HW::ap_const_boolean_1 = true;

Filter_HW::Filter_HW(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Temp_U = new Filter_HW_Temp("Temp_U");
    Temp_U->clk(ap_clk);
    Temp_U->reset(ap_rst);
    Temp_U->address0(Temp_address0);
    Temp_U->ce0(Temp_ce0);
    Temp_U->we0(Temp_we0);
    Temp_U->d0(grp_Filter_horizontal_HW_fu_20_Output_r_d0);
    Temp_U->q0(Temp_q0);
    Temp_U->address1(grp_Filter_vertical_fu_28_Input_r_address1);
    Temp_U->ce1(Temp_ce1);
    Temp_U->q1(Temp_q1);
    grp_Filter_horizontal_HW_fu_20 = new Filter_horizontal_HW("grp_Filter_horizontal_HW_fu_20");
    grp_Filter_horizontal_HW_fu_20->ap_clk(ap_clk);
    grp_Filter_horizontal_HW_fu_20->ap_rst(ap_rst);
    grp_Filter_horizontal_HW_fu_20->ap_start(grp_Filter_horizontal_HW_fu_20_ap_start);
    grp_Filter_horizontal_HW_fu_20->ap_done(grp_Filter_horizontal_HW_fu_20_ap_done);
    grp_Filter_horizontal_HW_fu_20->ap_idle(grp_Filter_horizontal_HW_fu_20_ap_idle);
    grp_Filter_horizontal_HW_fu_20->ap_ready(grp_Filter_horizontal_HW_fu_20_ap_ready);
    grp_Filter_horizontal_HW_fu_20->Input_r_address0(grp_Filter_horizontal_HW_fu_20_Input_r_address0);
    grp_Filter_horizontal_HW_fu_20->Input_r_ce0(grp_Filter_horizontal_HW_fu_20_Input_r_ce0);
    grp_Filter_horizontal_HW_fu_20->Input_r_q0(Input_r_q0);
    grp_Filter_horizontal_HW_fu_20->Input_r_address1(grp_Filter_horizontal_HW_fu_20_Input_r_address1);
    grp_Filter_horizontal_HW_fu_20->Input_r_ce1(grp_Filter_horizontal_HW_fu_20_Input_r_ce1);
    grp_Filter_horizontal_HW_fu_20->Input_r_q1(Input_r_q1);
    grp_Filter_horizontal_HW_fu_20->Output_r_address0(grp_Filter_horizontal_HW_fu_20_Output_r_address0);
    grp_Filter_horizontal_HW_fu_20->Output_r_ce0(grp_Filter_horizontal_HW_fu_20_Output_r_ce0);
    grp_Filter_horizontal_HW_fu_20->Output_r_we0(grp_Filter_horizontal_HW_fu_20_Output_r_we0);
    grp_Filter_horizontal_HW_fu_20->Output_r_d0(grp_Filter_horizontal_HW_fu_20_Output_r_d0);
    grp_Filter_vertical_fu_28 = new Filter_vertical("grp_Filter_vertical_fu_28");
    grp_Filter_vertical_fu_28->ap_clk(ap_clk);
    grp_Filter_vertical_fu_28->ap_rst(ap_rst);
    grp_Filter_vertical_fu_28->ap_start(grp_Filter_vertical_fu_28_ap_start);
    grp_Filter_vertical_fu_28->ap_done(grp_Filter_vertical_fu_28_ap_done);
    grp_Filter_vertical_fu_28->ap_idle(grp_Filter_vertical_fu_28_ap_idle);
    grp_Filter_vertical_fu_28->ap_ready(grp_Filter_vertical_fu_28_ap_ready);
    grp_Filter_vertical_fu_28->Input_r_address0(grp_Filter_vertical_fu_28_Input_r_address0);
    grp_Filter_vertical_fu_28->Input_r_ce0(grp_Filter_vertical_fu_28_Input_r_ce0);
    grp_Filter_vertical_fu_28->Input_r_q0(Temp_q0);
    grp_Filter_vertical_fu_28->Input_r_address1(grp_Filter_vertical_fu_28_Input_r_address1);
    grp_Filter_vertical_fu_28->Input_r_ce1(grp_Filter_vertical_fu_28_Input_r_ce1);
    grp_Filter_vertical_fu_28->Input_r_q1(Temp_q1);
    grp_Filter_vertical_fu_28->Output_r_address0(grp_Filter_vertical_fu_28_Output_r_address0);
    grp_Filter_vertical_fu_28->Output_r_ce0(grp_Filter_vertical_fu_28_Output_r_ce0);
    grp_Filter_vertical_fu_28->Output_r_we0(grp_Filter_vertical_fu_28_Output_r_we0);
    grp_Filter_vertical_fu_28->Output_r_d0(grp_Filter_vertical_fu_28_Output_r_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Input_r_address0);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Input_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Input_r_address1);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Input_r_address1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Input_r_ce0);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Input_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Input_r_ce1);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Input_r_ce1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Output_r_address0);
    sensitive << ( grp_Filter_vertical_fu_28_Output_r_address0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Output_r_ce0);
    sensitive << ( grp_Filter_vertical_fu_28_Output_r_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Output_r_d0);
    sensitive << ( grp_Filter_vertical_fu_28_Output_r_d0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Output_r_we0);
    sensitive << ( grp_Filter_vertical_fu_28_Output_r_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Temp_address0);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Output_r_address0 );
    sensitive << ( grp_Filter_vertical_fu_28_Input_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Temp_ce0);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Output_r_ce0 );
    sensitive << ( grp_Filter_vertical_fu_28_Input_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Temp_ce1);
    sensitive << ( grp_Filter_vertical_fu_28_Input_r_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Temp_we0);
    sensitive << ( grp_Filter_horizontal_HW_fu_20_Output_r_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_Filter_vertical_fu_28_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_Filter_vertical_fu_28_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_Filter_horizontal_HW_fu_20_ap_start);
    sensitive << ( ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start );

    SC_METHOD(thread_grp_Filter_vertical_fu_28_ap_start);
    sensitive << ( ap_reg_grp_Filter_vertical_fu_28_ap_start );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_Filter_horizontal_HW_fu_20_ap_done );
    sensitive << ( grp_Filter_vertical_fu_28_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start = SC_LOGIC_0;
    ap_reg_grp_Filter_vertical_fu_28_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Filter_HW_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Input_r_address0, "(port)Input_r_address0");
    sc_trace(mVcdFile, Input_r_ce0, "(port)Input_r_ce0");
    sc_trace(mVcdFile, Input_r_q0, "(port)Input_r_q0");
    sc_trace(mVcdFile, Input_r_address1, "(port)Input_r_address1");
    sc_trace(mVcdFile, Input_r_ce1, "(port)Input_r_ce1");
    sc_trace(mVcdFile, Input_r_q1, "(port)Input_r_q1");
    sc_trace(mVcdFile, Output_r_address0, "(port)Output_r_address0");
    sc_trace(mVcdFile, Output_r_ce0, "(port)Output_r_ce0");
    sc_trace(mVcdFile, Output_r_we0, "(port)Output_r_we0");
    sc_trace(mVcdFile, Output_r_d0, "(port)Output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, Temp_address0, "Temp_address0");
    sc_trace(mVcdFile, Temp_ce0, "Temp_ce0");
    sc_trace(mVcdFile, Temp_we0, "Temp_we0");
    sc_trace(mVcdFile, Temp_q0, "Temp_q0");
    sc_trace(mVcdFile, Temp_ce1, "Temp_ce1");
    sc_trace(mVcdFile, Temp_q1, "Temp_q1");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_ap_start, "grp_Filter_horizontal_HW_fu_20_ap_start");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_ap_done, "grp_Filter_horizontal_HW_fu_20_ap_done");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_ap_idle, "grp_Filter_horizontal_HW_fu_20_ap_idle");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_ap_ready, "grp_Filter_horizontal_HW_fu_20_ap_ready");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Input_r_address0, "grp_Filter_horizontal_HW_fu_20_Input_r_address0");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Input_r_ce0, "grp_Filter_horizontal_HW_fu_20_Input_r_ce0");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Input_r_address1, "grp_Filter_horizontal_HW_fu_20_Input_r_address1");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Input_r_ce1, "grp_Filter_horizontal_HW_fu_20_Input_r_ce1");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Output_r_address0, "grp_Filter_horizontal_HW_fu_20_Output_r_address0");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Output_r_ce0, "grp_Filter_horizontal_HW_fu_20_Output_r_ce0");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Output_r_we0, "grp_Filter_horizontal_HW_fu_20_Output_r_we0");
    sc_trace(mVcdFile, grp_Filter_horizontal_HW_fu_20_Output_r_d0, "grp_Filter_horizontal_HW_fu_20_Output_r_d0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_ap_start, "grp_Filter_vertical_fu_28_ap_start");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_ap_done, "grp_Filter_vertical_fu_28_ap_done");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_ap_idle, "grp_Filter_vertical_fu_28_ap_idle");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_ap_ready, "grp_Filter_vertical_fu_28_ap_ready");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Input_r_address0, "grp_Filter_vertical_fu_28_Input_r_address0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Input_r_ce0, "grp_Filter_vertical_fu_28_Input_r_ce0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Input_r_address1, "grp_Filter_vertical_fu_28_Input_r_address1");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Input_r_ce1, "grp_Filter_vertical_fu_28_Input_r_ce1");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Output_r_address0, "grp_Filter_vertical_fu_28_Output_r_address0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Output_r_ce0, "grp_Filter_vertical_fu_28_Output_r_ce0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Output_r_we0, "grp_Filter_vertical_fu_28_Output_r_we0");
    sc_trace(mVcdFile, grp_Filter_vertical_fu_28_Output_r_d0, "grp_Filter_vertical_fu_28_Output_r_d0");
    sc_trace(mVcdFile, ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start, "ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_reg_grp_Filter_vertical_fu_28_ap_start, "ap_reg_grp_Filter_vertical_fu_28_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("Filter_HW.hdltvin.dat");
    mHdltvoutHandle.open("Filter_HW.hdltvout.dat");
}

Filter_HW::~Filter_HW() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Temp_U;
    delete grp_Filter_horizontal_HW_fu_20;
    delete grp_Filter_vertical_fu_28;
}

void Filter_HW::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Filter_horizontal_HW_fu_20_ap_ready.read())) {
            ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Filter_vertical_fu_28_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_reg_grp_Filter_vertical_fu_28_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Filter_vertical_fu_28_ap_ready.read())) {
            ap_reg_grp_Filter_vertical_fu_28_ap_start = ap_const_logic_0;
        }
    }
}

void Filter_HW::thread_Input_r_address0() {
    Input_r_address0 = grp_Filter_horizontal_HW_fu_20_Input_r_address0.read();
}

void Filter_HW::thread_Input_r_address1() {
    Input_r_address1 = grp_Filter_horizontal_HW_fu_20_Input_r_address1.read();
}

void Filter_HW::thread_Input_r_ce0() {
    Input_r_ce0 = grp_Filter_horizontal_HW_fu_20_Input_r_ce0.read();
}

void Filter_HW::thread_Input_r_ce1() {
    Input_r_ce1 = grp_Filter_horizontal_HW_fu_20_Input_r_ce1.read();
}

void Filter_HW::thread_Output_r_address0() {
    Output_r_address0 = grp_Filter_vertical_fu_28_Output_r_address0.read();
}

void Filter_HW::thread_Output_r_ce0() {
    Output_r_ce0 = grp_Filter_vertical_fu_28_Output_r_ce0.read();
}

void Filter_HW::thread_Output_r_d0() {
    Output_r_d0 = grp_Filter_vertical_fu_28_Output_r_d0.read();
}

void Filter_HW::thread_Output_r_we0() {
    Output_r_we0 = grp_Filter_vertical_fu_28_Output_r_we0.read();
}

void Filter_HW::thread_Temp_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Temp_address0 = grp_Filter_vertical_fu_28_Input_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Temp_address0 = grp_Filter_horizontal_HW_fu_20_Output_r_address0.read();
    } else {
        Temp_address0 = "XXXXXXXXXXXXXXXXXXX";
    }
}

void Filter_HW::thread_Temp_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Temp_ce0 = grp_Filter_vertical_fu_28_Input_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Temp_ce0 = grp_Filter_horizontal_HW_fu_20_Output_r_ce0.read();
    } else {
        Temp_ce0 = ap_const_logic_0;
    }
}

void Filter_HW::thread_Temp_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Temp_ce1 = grp_Filter_vertical_fu_28_Input_r_ce1.read();
    } else {
        Temp_ce1 = ap_const_logic_0;
    }
}

void Filter_HW::thread_Temp_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Temp_we0 = grp_Filter_horizontal_HW_fu_20_Output_r_we0.read();
    } else {
        Temp_we0 = ap_const_logic_0;
    }
}

void Filter_HW::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Filter_HW::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Filter_HW::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Filter_HW::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Filter_HW::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_Filter_vertical_fu_28_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Filter_HW::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Filter_HW::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_Filter_vertical_fu_28_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Filter_HW::thread_grp_Filter_horizontal_HW_fu_20_ap_start() {
    grp_Filter_horizontal_HW_fu_20_ap_start = ap_reg_grp_Filter_horizontal_HW_fu_20_ap_start.read();
}

void Filter_HW::thread_grp_Filter_vertical_fu_28_ap_start() {
    grp_Filter_vertical_fu_28_ap_start = ap_reg_grp_Filter_vertical_fu_28_ap_start.read();
}

void Filter_HW::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_Filter_horizontal_HW_fu_20_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_Filter_vertical_fu_28_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

void Filter_HW::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Input_r_address0\" :  \"" << Input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Input_r_ce0\" :  \"" << Input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Input_r_q0\" :  \"" << Input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Input_r_address1\" :  \"" << Input_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Input_r_ce1\" :  \"" << Input_r_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Input_r_q1\" :  \"" << Input_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Output_r_address0\" :  \"" << Output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Output_r_ce0\" :  \"" << Output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Output_r_we0\" :  \"" << Output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Output_r_d0\" :  \"" << Output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

